CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY,
  customer VARCHAR(255) NOT NULL,
  phone VARCHAR(12) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE,
  is_dleted BOOLEAN NOT NULL DEFAULT FALSE,
);